<?php


use Phinx\Migration\AbstractMigration;

class SeedSomeItems extends AbstractMigration {
    public function up() {
        $this->table('items')->insert($this->getRows())->save();
    }

    private function getRows() {
        return [
            // Weapons
            [
                'name' => '"Rude Ruby"',
                'description' => "Granny's pink punisher. Custom made pistol, themed after Granny's favorite color. Fast fire rate but low accuracy",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Concept 5',
                'description' => 'Kronstadt produced firearm. Used to test Kronstadt android systems. With automatic fire and fairly low recoil.',
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Custom 5mm',
                'description' => 'A concealable pistol. Ergonomically designed to pass pat-downs and frisking attempts. Utilizes caseless ammunition and cannot be reloaded while in the field.',
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HWK21',
                'description' => "This is a breach-and-clear handgun that can quickly take out a number of targets with precise " .
                    "headshots. Great for clearing a room without escalating the fight. It's steady, quick, and excellent " .
                    "for close-quarter combat.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HWK 21 Mk II',
                'description' => "A modern light pistol. Rapid firing with good magazine capacity. This one with the " .
                    "signature Mk II look.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HWK 21 Covert',
                'description' => "A modern light pistol with camouflage details. Rapid firing with good magazine capacity.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19',
                'description' => "A tactical pistol. Custom slide. Low rate of fire with high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 F/A',
                'description' => "A tactical pistol. Custom slide. Capable of automatic fire.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 F/A Stealth',
                'description' => "A tactical suppressed pistol for high-intensity engagements. Custom slide. " .
                    "Fully automatic mechanism.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 Black Lilly',
                'description' => "A tactical pistol. Custom slide with suppressor. Low rate of fire, with high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 Silverballer',
                'description' => "A tactical pistol Custom slide. Low rate of fire with high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 Silverballer Mk II',
                'description' => "A tactical pistol. Custom slide with suppressor. Low rate of fire, with high damage. " .
                    "This one has the signature Mk II look.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'ICA19 Chrome',
                'description' => "A tactical pistol. Custom slide. Low rate of fire with high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Striker',
                'description' => "A magnum pistol. Body piercing rounds. Low rate of fire, and very high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Krugermeier 2-2',
                'description' => "A low velocity, small caliber pistol. Originally designed for special-forces " .
                    "use and to make as little noise as possible. Ineffective at medium-to-long ranges.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Kalmer 1 - Tranquilizer',
                'description' => "South African produced dart gun. Will sedate anyone it hits.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'DAK X2 Covert',
                'description' => "A one handed suppressed machine gun. Lightweight, with excellent rate of fire but " .
                    "low precision.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-SMG',
                'description' => "A modern submachine gun. Lightweight, with excellent rate of fire and precision.",
                    'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-SMG Mk II',
                'description' => "A modern machine gun. Lightweight, with excellent rate of fire and precision. This " .
                    "one with the signature Mk II look.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-SMG S',
                'description' => "A modern suppressed machine gun. Lightweight, with excellent rate of fire and precision.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-SMG Covert',
                'description' => "A modern submachine gun. Lightweight, with excellent rate of fire and precision.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Bartoli 12G Short H',
                'description' => "A U.S. production pump-action shotgun. Produced for domestic and international markets.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Enram HV',
                'description' => "A modern bullpup shotgun. Agile and effective at close ranges. Fast fire rate and tight spread.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Enram HV CM',
                'description' => "A modern bullpup shotgun. Agile and effective at close ranges. Fast fire rate and tight spread.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Enram HV Covert',
                'description' => "A modern silenced bullpup shotgun. Agile and effective at close ranges. Fast fire rate and tight spread.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Enram HV Covert Mk II',
                'description' => "A modern silenced bullpup shotgun. Agile and effective at close ranges. Fast fire " .
                    "rate and tight spread. This one has the signature Mk II look.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'RS-15',
                'description' => "A modern edition of a widely distributed assault rifle. Fully automatic. Equipped " .
                    "with an effective suppressor.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Shashka A33 H',
                'description' => "A modern assault rife. Fully automatic. With high damage but only semi-accurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-4 AR Auto',
                'description' => "A modern bullpup assault rife. Fully automatic. Accurate, with a high fire rate and " .
                    "excellent damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-4 AR Auto Mk I',
                'description' => "A modern bullpup assault rife. Fully automatic. Accurate, with a high fire rate and " .
                    "excellent damage. This one with the signature Mk II look.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-4 AR Stealth',
                'description' => "A modern bullpup assault rife. Fully automatic. Has a powerful suppressor attached.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'TAC-4 S/A',
                'description' => "A modern bullpup battle rifle. Semi-automatic. Accurate, with good range and excellent damage",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => '"El Matador"',
                'description' => "Rico Delgado's own gun. Body piercing rounds. Low rate of fire, and very high damage.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Hackl 9S',
                'description' => "Austrian produced light tactical pistol. Underpowered.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Hackl 9R',
                'description' => "Austrian produced pistol.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Hackl 9S Covert',
                'description' => "Austrian produced light tactical covert pistol. Underpowered.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Bartoli 75S',
                'description' => "A European light tactical pistol. Underpowered.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Bartoli 75R',
                'description' => "A European light tactical pistol. Underpowered.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'DAK X2',
                'description' => "A one handed machine gun. Lightweight, with excellent rate of fire but low precision.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HX-7',
                'description' => "A submachine gun. Lightweight and inaccurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HX-7 Covert',
                'description' => "A submachine gun. Lightweight, covert, and inaccurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'HX-10',
                'description' => "A submachine gun. Lightweight and inaccurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Tactical Bartoli 12G',
                'description' => "A U.S.-produced pump-action shotgun. Effective at close ranges.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Bartoli 12G',
                'description' => "A U.S. produced pump-action shotgun. Produced for domestic and international markets.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Fusil G1-4',
                'description' => "The Fusil G2's predecessor. Widely exported. Chambered for 5.56mm.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Fusil G2',
                'description' => "A French-made assault rifle. Fully automatic.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Fusil G1-4/C',
                'description' => "A French assault rifle. Chambered for 5.56mm. Built for close quarter engagement.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Shashka A33',
                'description' => "A modern assault rifle. Fully automatic. With high damage but only semi-accurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
            [
                'name' => 'Shashka A33 Gold',
                'description' => "A modern assault rifle with gold features. Fully automatic. With high damage but only semi-accurate.",
                'type' => 'Weapons and Tools',
                'icon' => 'firearm',
                'group' => 'Firearm',
            ],
			// Sabotage
			[
                'name' => 'Chandelier',
				'target' => '',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Coconuts',
				'target' => '',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Gas Canister',
				'target' => 'Loosen the Valve',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Gasoline Drum',
				'target' => 'Puncture',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Gas Heater Lamp',
				'target' => 'Loosen the Valve',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Gas Valve',
				'target' => 'Release Gas',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Phonebooth',
				'target' => 'Short-Circuit',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Scooter',
				'target' => 'Create Oil Leak',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Stove',
				'target' => 'Start Gas Leak',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			[
                'name' => 'Wire Plug',
				'target' => 'Expose Wire',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'sabotage',
                'group' => 'Sabotage',
            ],
			// Distractions
			[
                'name' => 'Faucet',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Forklift',
				'target' => 'Start Alarm',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Fuse Box',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Generator',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Radio',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Sink',
				'target' => 'Overflow Sink',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Sound System',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Toilet Control Panel',
				'target' => 'Tamper',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'TV',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			[
                'name' => 'Vacuum Cleaner',
				'target' => 'Turn On/Off',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'distraction',
                'group' => 'Distraction',
            ],
			// Alarm
			[
                'name' => 'Fire Alarm',
				'target' => 'Trigger Fire Alarm',
                'description' => "",
                'type' => 'Points of Interest',
                'icon' => 'alarm',
                'group' => 'Alarm',
            ],
			// Hiding Spot
			[
                'name' => 'Hiding Spot',
                'type' => 'Points of Interest',
                'icon' => 'hiding-spot',
                'group' => 'Hiding Spot',
            ],
			// Conceal Item
			[
                'name' => 'Conceal Item',
                'type' => 'Points of Interest',
                'icon' => 'conceal-item',
                'group' => 'Conceal Item',
            ],
			// Weapon Crate
			[
                'name' => 'Weapon Crate',
                'type' => 'Points of Interest',
                'icon' => 'weapon-crate',
                'group' => 'Weapon Crate',
            ],
			// Camera
			[
                'name' => 'Camera',
                'type' => 'Points of Interest',
                'icon' => 'camera',
                'group' => 'Camera',
            ],
			// Lethal Melee
			[
                'name' => 'Amputation Knife',
                'type' => 'Weapons and Tools',
				'description' => 'An antique amputation knife. Renaissance construction. Weighted blade. Lethal when thrown or used in close combat.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Circumcision Knife',
                'type' => 'Weapons and Tools',
				'description' => 'A circumcision knife. Small but effective in close combat, or when thrown, to eliminate a target.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Cleaver',
                'type' => 'Weapons and Tools',
				'description' => 'A kitchen cleaver. Lethal when thrown or used in close combat. Unsuspicious when carried by kitchen staff.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Combat Knife',
                'type' => 'Weapons and Tools',
				'description' => 'A military knife. Stainless steel. Effective in close-quarters engagements.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Battle Axe',
                'type' => 'Weapons and Tools',
				'description' => 'A historical axe. Designed for lethality when thrown or used in close combat. Highly obvious.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Fire Axe',
                'type' => 'Weapons and Tools',
				'description' => 'A fire axe. Lethal when used in melee or thrown.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Folding Knife',
                'type' => 'Weapons and Tools',
				'description' => 'A folding knife. Can be thrown or effectively used in close combat to eliminate a target.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Hatchet',
                'type' => 'Weapons and Tools',
				'description' => 'A long-handled hatchet. Lethal in close combat or when thrown.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Katana',
                'type' => 'Weapons and Tools',
				'description' => 'A Japanese-style sword. Modern, high-strength steel blade. Lethal in all engagement scenarios.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Kitchen Knife',
                'type' => 'Weapons and Tools',
				'description' => 'A kitchen knife. Deadly in close combat or when thrown. Unsuspicious when carried by kitchen staff.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Old Axe',
                'type' => 'Weapons and Tools',
				'description' => 'An old axe. Lethal in melee. Can be thrown.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Saber',
                'type' => 'Weapons and Tools',
				'description' => 'A cavalry saber. Napoleonic era. Effective when used in close combat.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Scalpel',
                'type' => 'Weapons and Tools',
				'description' => 'A scalpel. Can be used in close combat, or thrown to eliminate a target.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Scissors',
                'type' => 'Weapons and Tools',
				'description' => 'Scissors. Can be used to eliminate a target in close combat or thrown for the same effect.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Screwdriver',
                'type' => 'Weapons and Tools',
				'description' => 'A screwdriver with an insulated handle. Can sabotage certain devices and installations, ' . 
					'or be used to create leaks. Can be thrown or used in close combat to eliminate a target.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			[
                'name' => 'Letter Opener',
                'type' => 'Weapons and Tools',
				'description' => 'A letter opener. Lightweight. Can be effectively used in close combat or thrown to eliminate a target.',
                'icon' => 'lethal-melee',
                'group' => 'Lethal Melee',
            ],
			// Non-lethal melee
            [
                'name' => 'Android Arm',
                'type' => 'Weapons and Tools',
                'description' => 'An android arm. Effective as a non-lethal, blunt weapon.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Baseball Bat',
                'type' => 'Weapons and Tools',
				'description' => 'A baseball bat. Non-lethal. Can be used to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Baseball',
                'type' => 'Weapons and Tools',
				'description' => 'A baseball. Can be thrown or used in melee combat to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Branding Iron',
                'type' => 'Weapons and Tools',
				'description' => 'A branding iron. Non-lethal. Can be used to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Bust',
                'type' => 'Weapons and Tools',
				'description' => 'A solid bust. Can be either thrown, used in close combat to knock an individual unconscious, or used as a distraction.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
            [
                'name' => 'Car Battery',
                'type' => 'Weapons and Tools',
                'description' => 'A car battery. Still has a small charge.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Coconut',
                'type' => 'Weapons and Tools',
				'description' => 'A coconut.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Cowboy Bust',
                'type' => 'Weapons and Tools',
				'description' => 'A solid bronze cowboy bust. Can knock a person unconscious when thrown or used as a melee weapon.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Crowbar',
                'type' => 'Weapons and Tools',
				'description' => 'A crowbar. Can be used to break locks. Can be thrown or used in close combat to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Hammer',
                'type' => 'Weapons and Tools',
				'description' => 'A lightweight hammer. Can be used in close combat or thrown to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Wrench',
                'type' => 'Weapons and Tools',
				'description' => 'A wrench. Useful to sabotage small vehicles and other installations. Can be thrown or used in close combat to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Hammer',
                'type' => 'Weapons and Tools',
				'description' => 'A lightweight hammer. Can be used in close combat or thrown to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Golf Club',
                'type' => 'Weapons and Tools',
				'description' => 'A golf club. Can be used as a weapon to knock an individual unconscious, or perform a takedown from behind.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Fire Poker',
                'type' => 'Weapons and Tools',
				'description' => 'A wrought-iron poker. Can be used to non-lethally incapacitate an individual either in close combat or from behind.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Mannequin Arm',
                'type' => 'Weapons and Tools',
				'description' => 'A mannequin arm. Can be used as a melee weapon to render people unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Police Baton',
                'type' => 'Weapons and Tools',
				'description' => 'A tonfa. Effective as a non-lethal, blunt weapon.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Pool Ball',
                'type' => 'Weapons and Tools',
				'description' => 'A solid pool ball. Can be thrown or used in close combat to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Shovel',
                'type' => 'Weapons and Tools',
				'description' => 'A shovel. Can be used in melee or thrown to create a distraction.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Soda Can',
                'type' => 'Weapons and Tools',
				'description' => 'A can of branded soda. Can be thrown to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Toy Tank',
                'type' => 'Weapons and Tools',
				'description' => 'A toy modeled after a tank. Can be used in melee or thrown to create a distraction.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Lead Pipe',
                'type' => 'Weapons and Tools',
				'description' => 'A lead pipe. Effective as a non-lethal, blunt weapon.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			[
                'name' => 'Brick',
                'type' => 'Weapons and Tools',
				'description' => 'A ubiquitous brick. Can be thrown or used in close combat to knock an individual unconscious.',
                'icon' => 'non-lethal-melee',
                'group' => 'Non-lethal Melee',
            ],
			// Explosive
            [
                'name' => 'Kronstadt Octane Booster',
                'type' => 'Weapons and Tools',
                'description' => 'A bottle of patented Kronstadt Octane Booster, guaranteed to send your car flying.',
                'icon' => 'explosive',
                'group' => 'Explosive',
            ],
			[
                'name' => 'Fire Extinguisher',
                'type' => 'Weapons and Tools',
				'description' => 'A fire extinguisher. Can be shot at to create an explosion that will be considered accidental. ' .
					'Heavy enough to knock an individual unconscious in close combat.',
                'icon' => 'explosive',
                'group' => 'Explosive',
            ],
			[
                'name' => 'Propane Flask',
                'type' => 'Weapons and Tools',
				'description' => 'A propane flask. Can be shot at to create an explosion that will be considered accidental. ' .
					'Heavy enough to knock an individual unconscious in close combat.',
                'icon' => 'explosive',
                'group' => 'Explosive',
            ],
			[
                'name' => 'Remote Explosive',
                'type' => 'Weapons and Tools',
				'description' => 'A medium explosive device. Detonated remotely. Can be mounted on most flat surfaces.',
                'icon' => 'explosive',
                'group' => 'Explosive',
            ],
			// Coin
			[
                'name' => 'Coin',
                'type' => 'Weapons and Tools',
				'description' => 'A solid coin. Heavy enough to cause an audible distraction when thrown.',
                'icon' => 'coin',
                'group' => 'Coin',
            ],
			// Poison
			[
                'name' => 'Emetic Rat Poison',
                'type' => 'Weapons and Tools',
				'description' => 'A box of rat poison. Non-lethal to humans. When administered, the individual will experience immediate nausea ' . 
					'and will seek a location to throw up in.',
                'icon' => 'poison-weapon',
                'group' => 'Poison',
            ],
			[
                'name' => 'Lethal Poison',
                'type' => 'Weapons and Tools',
				'description' => 'A vial of poison. Contains a single dose of a lethal poison. Will result in immediate death of the target. ' . 
					'Can be administered via food or drink.',
                'icon' => 'poison-weapon',
                'group' => 'Poison',
            ],
            [
                'name' => 'Lethal Poison Pill Jar',
                'type' => 'Weapons and Tools',
                'description' => 'A jar of pills. Contains a single dose of lethal poison. Can be dissolved in food or drinks.',
                'icon' => 'poison-weapon',
                'group' => 'Poison',
            ],
            [
                'name' => 'Lethal Poisonous Frog',
                'type' => 'Weapons and Tools',
                'description' => "A brightly colored frog. It's beautiful, but deadly.",
                'icon' => 'poison-weapon',
                'group' => 'Poison',
            ],
			// Apricot
			[
                'name' => 'Apricot',
                'type' => 'Weapons and Tools',
				'description' => 'A simple apricot. Big enough to cause an audible distraction when thrown.',
                'icon' => 'apricot',
                'group' => 'Apricot',
            ],
        ];
    }

    public function down() {
        foreach ($this->getRows() as $row) {
            $this->execute("DELETE FROM `items` WHERE `name` = '" . $row['name'] ."'");
        }
    }
}
