include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - Utilities
  - Prod Deploy
  - Stage Deploy

before_script:
  - apt-get update
  - apt-get install -y lftp
  - apt-get install -y zip
  - apt-get install -y curl
  - apt-get install -y nodejs
  - apt-get install -y wget

Prod Deploy API:
  image: php:7.2
  stage: Prod Deploy
  only:
    - master
  script:
    - cd api/
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-dev
    - cd ../
    - cd ci/prod/
    - bash deploy_backend.sh
  environment:
    name: Production API
    url: https://www.hitman2maps.com/api
  artifacts:
    paths:
    - backend/

Prod Deploy Frontend:
  image: node:10
  stage: Prod Deploy
  only:
    - master
  script:
    - npm ci
    - npm run build
    - cd ci/prod/
    - bash deploy_frontend.sh
  environment:
    name: Production Frontend
    url: https://www.hitman2maps.com
  artifacts:
    paths:
    - frontend/

Stage Deploy API:
  image: php:7.2
  stage: Stage Deploy
  only:
    - stage
  script:
    - cd api/
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-dev
    - cd ../
    - cd ci/stage/
    - bash deploy_backend.sh
  environment:
    name: Staging API
    url: https://test.hitman2maps.com/api
  artifacts:
    paths:
    - backend/

Stage Deploy Frontend:
  image: node:10
  stage: Stage Deploy
  only:
    - stage
  script:
    - npm ci
    - npm run staging
    - cd ci/stage/
    - bash deploy_frontend.sh
  environment:
    name: Staging Frontend
    url: https://test.hitman2maps.com
  artifacts:
    paths:
      - frontend/


Refresh Stage DB:
  image: php:7.2
  stage: Utilities
  only:
  - stage
  when: manual
  script:
  - wget https://test.hitman2maps.com/refresh-stage-db.php?access-key=$ACCESS_KEY
