stages:
  - deploy
  - utilities

before_script:
  - apt-get update
  - apt-get install -y lftp
  - apt-get install -y zip
  - apt-get install -y wget
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - apt-get install -y nodejs

deploy_prod:
  image: php:7.2
  only:
    - master
  stage: deploy
  script:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-dev
    - cd ci/
    - bash deploy_to_prod.sh
  environment:
    name: Production
    url: https://www.hitman2maps.com
  artifacts:
    paths:
      - latest_build/

deploy_stage:
  image: php:7.2
  stage: deploy
  only:
    - stage
  script:
    - cd api/
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-dev
    - cd ../
    - cd ci/
    - bash deploy_to_stage.sh
  environment:
    name: Staging
    url: https://test.hitman2maps.com
  artifacts:
    paths:
      - latest_build/

refresh_stage_db:
  image: php:7.2
  stage: utilities
  only:
    - stage
  when: manual
  script:
    - wget https://test.hitman2maps.com/refresh-stage-db.php?access-key=$ACCESS_KEY
