stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y lftp
  - apt-get install -y zip
  - apt-get install -y wget

deploy_prod:
  image: php:7.2
  only:
    - master
  stage: deploy
  script:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-dev
    - cd ci/
    - bash deploy_to_prod.sh
  environment:
    name: Production
    url: https://www.hitman2maps.com
  artifacts:
    paths:
      - latest_build/
